"""Create the task table

Revision ID: 129b4c096020
Revises: 
Create Date: 2024-02-02 16:10:53.296797

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "129b4c096020"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False, comment="Идентификатор задачи."),
        sa.Column("status", sa.Integer(), nullable=False, comment="Статус задачи в цифровом виде."),
        sa.Column(
            "ipr",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Результат вычисления ipr.",
        ),
        sa.Column(
            "vlp",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Результат вычисления vlp.",
        ),
        sa.Column(
            "nodal_analysis",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Результат вычисления узлового анализа.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("TIMEZONE('utc', now())"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    # ### end Alembic commands ###
